<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = PATH_site;

return array(
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'Extcode\\Cart\\' => array($typo3InstallDir . 'typo3conf/ext/cart/Classes'),
    'Froemer\\Offlineshop\\' => array($typo3InstallDir . 'typo3conf/ext/offlineshop/Classes'),
    'MASK\\Mask\\' => array($typo3InstallDir . 'typo3conf/ext/mask/Classes'),
    'PhpParser\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Resources/Private/PHP/PHP-Parser/lib/PhpParser'),
);
