<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cangemarket"
 *
 * Auto generated by Extension Builder 2018-07-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Cange Supermarket Template',
    'description' => 'Template for an eShop',
    'category' => 'templates',
    'author' => 'F Römer',
    'author_email' => '',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
